name: Next.js CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install dependencies
        run: |
          cd frontend
          npm install --force
      - name: Run Lint
        run: |
          cd frontend
          npm run lint
      - name: Build Next.js app
        run: |
          cd frontend
          npm run build
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.TOKEN_VERCEL }}
        run: |
          cd frontend
          npx vercel deploy --prod --token $VERCEL_TOKEN --confirm









